import type {
  CommercialInfo,
  Inquiry,
  InspectionReport,
  MachineDetails,
  MachineSpecs,
  Order,
  Product,
  SellRequest,
  SellerInfo,
  User,
} from "./types";

export { CATEGORIES } from "./options";
export type { Category } from "./options";
export type * from "./types";

const IMG = "/machines";

/* ------------------------------------------------------------- builders -- */
/* Defaults keep the fixtures readable; each record overrides what matters. */

function seller(partial: Partial<SellerInfo>): SellerInfo {
  return {
    name: "",
    company: "",
    mobile: "",
    whatsapp: "",
    email: "",
    gstNumber: "",
    panNumber: "",
    address: "",
    city: "",
    state: "",
    pincode: "",
    ...partial,
  };
}

function details(partial: Partial<MachineDetails>): MachineDetails {
  return {
    machineType: "",
    installationYear: "",
    countryOfOrigin: "",
    controller: "",
    numberOfAxis: "",
    machineCapacity: "",
    powerRequirement: "",
    maxSpindleSpeed: "",
    weight: "",
    workingStatus: "Running",
    maintenanceStatus: "Regular",
    lastServiceDate: "",
    accessoriesIncluded: "",
    serialNumber: "",
    ...partial,
  };
}

function specs(partial: Partial<MachineSpecs>): MachineSpecs {
  return {
    tableSize: "",
    lubricationSystem: "",
    electricalPanelCondition: "",
    toolMagazineCapacity: "",
    servoMotors: "",
    toolChangerType: "",
    ballScrewCondition: "",
    coolantSystem: "",
    guideways: "",
    hydraulicSystem: "",
    otherSpecifications: "",
    ...partial,
  };
}

function commercial(partial: Partial<CommercialInfo>): CommercialInfo {
  return {
    negotiable: true,
    gstAvailable: true,
    taxInvoiceAvailable: true,
    financePending: false,
    deliveryAvailable: true,
    loadingAvailable: true,
    ownerType: "1st Owner",
    ...partial,
  };
}

const FULL_INSPECTION: InspectionReport = {
  inspectorName: "R. Deshmukh",
  inspectedOn: "2026-08-03",
  remarks:
    "Machine holds tolerance within spec. Minor cosmetic wear on the front door. Recommended for listing without reservation.",
  points: [
    { point: "Machine Accuracy", rating: "Excellent" },
    { point: "Spindle Condition", rating: "Excellent" },
    { point: "Axis Movement (X/Y/Z)", rating: "Excellent" },
    { point: "Ball Screw Condition", rating: "Good" },
    { point: "Tool Changer Condition", rating: "Good" },
    { point: "Coolant System", rating: "Good" },
    { point: "Hydraulic System", rating: "Not Applicable" },
    { point: "Electrical Panel", rating: "Excellent" },
    { point: "Leakage", rating: "Good", remark: "No active leaks observed" },
    { point: "Noise", rating: "Good" },
    { point: "Vibration", rating: "Excellent" },
    { point: "Overall Condition", rating: "Excellent" },
  ],
};

/* ------------------------------------------------------------- products -- */

export const PRODUCTS: Product[] = [
  {
    id: "MS-1001",
    title: "DMG MORI DMU 50",
    brand: "DMG MORI",
    type: "5-Axis Universal Machining Center",
    category: "CNC Machines",
    categories: ["CNC", "Milling"],
    year: "2019",
    price: 14500000,
    location: "Pune, MH",
    condition: "Excellent",
    hours: "6,400",
    origin: "Germany",
    status: "Live",
    views: 412,
    inquiries: 9,
    seller: "Aerotech Solutions",
    listedOn: "2026-06-12",
    badge: "EXCELLENT CONDITION",
    priceNote: "EXCL. SHIPPING",
    ctaLabel: "Request Technical Audit",
    images: [`${IMG}/dmg_cmx_1100v.jpg`, `${IMG}/workshop_banner.jpg`],
    overview: [
      "The DMU 50 is DMG MORI's workhorse 5-axis universal machining center, built around a swivel rotary table that lets you finish complex parts in a single setup.",
      "This unit has been in a temperature-controlled toolroom since new, runs Siemens 840D, and comes with the through-spindle coolant package and full documentation.",
    ],
    features: [
      "5-Axis Simultaneous",
      "Through Spindle Coolant",
      "HSK-A63",
      "Chip Conveyor",
    ],
    description:
      "Single owner, toolroom use only. Full service history available on request.",
    sellerInfo: seller({
      name: "Marcus V. Sterling",
      company: "Aerotech Solutions Inc.",
      mobile: "+91 98220 41155",
      whatsapp: "+91 98220 41155",
      email: "marcus@aerotech.in",
      gstNumber: "27AABCA9021M1Z8",
      panNumber: "AABCA9021M",
      address: "Plot 18, Chakan Industrial Area Phase II",
      city: "Pune",
      state: "Maharashtra",
      pincode: "410501",
    }),
    details: details({
      machineType: "5-Axis Universal Machining Center",
      installationYear: "2019",
      countryOfOrigin: "Germany",
      controller: "Siemens 840D solutionline",
      numberOfAxis: "5 Axis (simultaneous)",
      machineCapacity: "650 / 520 / 475 mm",
      powerRequirement: "3-Phase 415V, 30 kVA",
      maxSpindleSpeed: "20,000 rpm",
      weight: "5,200 kg",
      lastServiceDate: "14 Jul 2026",
      accessoriesIncluded:
        "HSK-A63 tool holders (24), coolant chiller, chip conveyor, manuals",
      serialNumber: "SN-DMU50-8842",
    }),
    specs: specs({
      tableSize: "Ø 630 mm swivel rotary",
      lubricationSystem: "Automatic centralised",
      electricalPanelCondition: "Excellent",
      toolMagazineCapacity: "30 tools",
      servoMotors: "Siemens 1FT7 — healthy",
      toolChangerType: "Chain magazine",
      ballScrewCondition: "Excellent, no backlash",
      coolantSystem: "Through spindle 40 bar",
      guideways: "Linear roller guides",
      hydraulicSystem: "Working",
      otherSpecifications: "Positioning accuracy ±0.005 mm, rapids 30 m/min",
    }),
    commercial: commercial({}),
    documents: [
      { name: "Original Invoice.pdf", size: "1.2 MB", category: "Original Invoice", uploadedOn: "12 Jun 2026" },
      { name: "Service History Log.pdf", size: "3.4 MB", category: "Service History", uploadedOn: "12 Jun 2026" },
      { name: "Operator Manual.pdf", size: "14.5 MB", category: "Machine Manual", uploadedOn: "12 Jun 2026" },
    ],
    requiredPhotos: ["Front View", "Back View", "Controller Panel", "Name Plate", "Chuck / Spindle", "Working Condition"],
    additionalRemarks: "Machine is under power and can be demonstrated under load at the seller site.",
  },
  {
    id: "MS-1002",
    title: "Mazak INTEGREX i-200ST",
    brand: "Yamazaki Mazak",
    type: "Multi-Tasking Turning Center",
    category: "CNC Machines",
    categories: ["CNC", "Multi-Tasking", "Lathe"],
    year: "2018",
    price: 21000000,
    location: "Bengaluru, KA",
    condition: "Good",
    hours: "11,800",
    origin: "Japan",
    status: "Live",
    views: 356,
    inquiries: 7,
    seller: "Precision Dynamics",
    listedOn: "2026-06-28",
    badge: "CERTIFIED",
    priceNote: "INSTALL INCLUDED",
    ctaLabel: "View Configuration Sheet",
    images: [`${IMG}/integrex_i200.jpg`, `${IMG}/okuma_genos.jpg`],
    overview: [
      "The INTEGREX i-200ST combines full turning capability with a B-axis milling spindle and a second turning spindle, so shafts and complex prismatic parts come off complete.",
      "Ideal for job shops moving from multi-operation routing to done-in-one manufacturing. Under AMC until 2027.",
    ],
    features: ["Done-In-One", "Y-Axis", "Sub Spindle", "Bar Feeder Ready"],
    description: "Twin-spindle multi-tasking centre with milling turret. Under AMC until 2027.",
    sellerInfo: seller({
      name: "Vikram Shetty",
      company: "Precision Dynamics",
      mobile: "+91 98450 66712",
      whatsapp: "+91 98450 66712",
      email: "vikram@precisiondyn.in",
      gstNumber: "29AAGCP5567L1ZR",
      panNumber: "AAGCP5567L",
      address: "44 Peenya Industrial Area Phase III",
      city: "Bengaluru",
      state: "Karnataka",
      pincode: "560058",
    }),
    details: details({
      machineType: "Multi-Tasking Turning Center",
      installationYear: "2018",
      countryOfOrigin: "Japan",
      controller: "Mazatrol Matrix 2",
      numberOfAxis: "6 Axis (X/Y/Z/B/C1/C2)",
      machineCapacity: "Ø 658 mm x 1,011 mm",
      powerRequirement: "3-Phase 415V, 45 kVA",
      maxSpindleSpeed: "12,000 rpm (milling)",
      weight: "9,800 kg",
      maintenanceStatus: "Regular",
      lastServiceDate: "02 Jun 2026",
      accessoriesIncluded: "Steady rest, bar feeder interface, tool holders",
      serialNumber: "SN-IGX200-2213",
    }),
    specs: specs({
      tableSize: "Not applicable",
      lubricationSystem: "Automatic centralised",
      electricalPanelCondition: "Good",
      toolMagazineCapacity: "36 tools",
      servoMotors: "Mazak AC servo — healthy",
      toolChangerType: "Drum magazine",
      ballScrewCondition: "Good",
      coolantSystem: "High pressure 70 bar",
      guideways: "Roller guideways",
      hydraulicSystem: "Working",
      otherSpecifications: "Y-axis ±105 mm, synchronised sub spindle",
    }),
    commercial: commercial({ ownerType: "Dealer", financePending: true }),
    documents: [
      { name: "Purchase Invoice.pdf", size: "0.9 MB", category: "Purchase Invoice", uploadedOn: "28 Jun 2026" },
      { name: "AMC Contract.pdf", size: "2.1 MB", category: "AMC Details", uploadedOn: "28 Jun 2026" },
    ],
    requiredPhotos: ["Front View", "Controller Panel", "Tool Magazine", "Chuck / Spindle"],
    additionalRemarks: "Buyer to arrange rigging. Seller can assist with loading.",
  },
  {
    id: "MS-1003",
    title: "Mazak HCN-4000",
    brand: "Yamazaki Mazak",
    type: "Horizontal Machining Center",
    category: "CNC Machines",
    categories: ["CNC", "HMC"],
    year: "2017",
    price: 10500000,
    location: "Chennai, TN",
    condition: "Good",
    hours: "14,200",
    origin: "Japan",
    status: "Under Offer",
    views: 288,
    inquiries: 5,
    seller: "Southern Machine Tools",
    listedOn: "2026-05-30",
    badge: "VERIFIED",
    priceNote: "EXCL. SHIPPING",
    ctaLabel: "Request Technical Audit",
    images: [`${IMG}/hmc_horizontal.jpg`, `${IMG}/dmg_mori_nhx.jpg`],
    overview: [
      "A twin-pallet horizontal machining center built for unattended production runs — load one pallet while the other cuts.",
      "This example has run a single-part family since installation and has complete AMC history from the Mazak service centre in Chennai.",
    ],
    features: ["Twin Pallet Changer", "Through Spindle Coolant", "Rigid Tapping", "Tool Breakage Detection"],
    description: "Single-part-family production use. Complete AMC history.",
    sellerInfo: seller({
      name: "Anitha Raman",
      company: "Southern Machine Tools",
      mobile: "+91 90031 77820",
      whatsapp: "+91 90031 77820",
      email: "anitha@southernmt.in",
      gstNumber: "33AAFCS2210H1ZP",
      panNumber: "AAFCS2210H",
      address: "72 Ambattur Industrial Estate",
      city: "Chennai",
      state: "Tamil Nadu",
      pincode: "600058",
    }),
    details: details({
      machineType: "Horizontal Machining Center",
      installationYear: "2017",
      countryOfOrigin: "Japan",
      controller: "Mazatrol SmoothG",
      numberOfAxis: "4 Axis (X/Y/Z/B)",
      machineCapacity: "560 / 640 / 640 mm",
      powerRequirement: "3-Phase 415V, 38 kVA",
      maxSpindleSpeed: "12,000 rpm",
      weight: "11,500 kg",
      lastServiceDate: "20 May 2026",
      accessoriesIncluded: "2 pallets, fixtures, chip conveyor",
      serialNumber: "SN-HCN4000-5517",
    }),
    specs: specs({
      tableSize: "400 x 400 mm pallet",
      lubricationSystem: "Automatic centralised",
      electricalPanelCondition: "Good",
      toolMagazineCapacity: "40 tools",
      servoMotors: "Mazak AC servo",
      toolChangerType: "Chain, random access",
      ballScrewCondition: "Good",
      coolantSystem: "Through spindle 20 bar",
      guideways: "Roller guideways",
      hydraulicSystem: "Working",
      otherSpecifications: "B-axis 1° indexing, rapids 50 m/min",
    }),
    commercial: commercial({ negotiable: false }),
    documents: [
      { name: "Original Invoice.pdf", size: "1.1 MB", category: "Original Invoice", uploadedOn: "30 May 2026" },
      { name: "Maintenance Records.pdf", size: "4.2 MB", category: "Maintenance Records", uploadedOn: "30 May 2026" },
    ],
    requiredPhotos: ["Front View", "Back View", "Controller Panel", "Tool Magazine", "Name Plate"],
    additionalRemarks: "Currently under offer from a Coimbatore buyer.",
  },
  {
    id: "MS-1004",
    title: "Haas VF-2SS",
    brand: "Haas Automation",
    type: "Super-Speed Vertical Machining Center",
    category: "VMC Centers",
    categories: ["VMC", "Milling"],
    year: "2021",
    price: 7050000,
    location: "Rajkot, GJ",
    condition: "Excellent",
    hours: "4,200",
    origin: "USA",
    status: "Live",
    views: 524,
    inquiries: 12,
    seller: "Fortune Gold Machine Tools",
    listedOn: "2026-07-02",
    badge: "EXCELLENT CONDITION",
    priceNote: "EXCL. SHIPPING",
    ctaLabel: "Request Technical Audit",
    images: [`${IMG}/haas_vf2ss.jpg`, `${IMG}/haas_vf2.jpg`, `${IMG}/workshop_banner.jpg`],
    overview: [
      "The VF-2SS is the super-speed variant of Haas's best-selling VMC — a 12,000 rpm inline direct-drive spindle and 35.5 m/min rapids make it a strong fit for high-mix aluminium work.",
      "Spindle replaced under warranty in 2024. Regular maintenance logged; minor cosmetic scratches on the front door panel.",
    ],
    features: ["Through Spindle Coolant", "Programmable Coolant", "Rigid Tapping", "High-Speed Machining"],
    description:
      "Excellent working condition. Spindle replaced in 2024. Regular maintenance logged. Minor cosmetic scratches on the front door panel.",
    sellerInfo: seller({
      name: "Pappu Singh",
      company: "Fortune Gold Machine Tools",
      mobile: "+91 84015 03169",
      whatsapp: "+91 84015 03169",
      email: "sales@fortunegold.in",
      gstNumber: "24AAACF1234K1ZV",
      panNumber: "AAACF1234K",
      address: "Fortune Gold, Metoda, Lodhika",
      city: "Rajkot",
      state: "Gujarat",
      pincode: "360021",
    }),
    details: details({
      machineType: "Vertical Machining Center",
      installationYear: "2021",
      countryOfOrigin: "USA",
      controller: "Haas Next Generation Control",
      numberOfAxis: "3 Axis",
      machineCapacity: "762 / 406 / 508 mm",
      powerRequirement: "3-Phase 415V, 22.4 kVA",
      maxSpindleSpeed: "12,000 rpm",
      weight: "3,175 kg",
      lastServiceDate: "18 Aug 2026",
      accessoriesIncluded:
        "Tool holders (20), coolant pump, chip auger, operator manual, levelling pads",
      serialNumber: "SN-9827346A",
    }),
    specs: specs({
      tableSize: "914 x 356 mm",
      lubricationSystem: "Automatic centralised",
      electricalPanelCondition: "Excellent",
      toolMagazineCapacity: "24+1 side mount",
      servoMotors: "Yaskawa AC servo — healthy",
      toolChangerType: "Side mount ATC",
      ballScrewCondition: "Excellent, no backlash",
      coolantSystem: "Through spindle 300 psi",
      guideways: "Linear guideways",
      hydraulicSystem: "Not applicable",
      otherSpecifications: "Rigid tapping, programmable coolant, CT 40 taper",
    }),
    commercial: commercial({}),
    documents: [
      { name: "Original Invoice.pdf", size: "1.2 MB", category: "Original Invoice", uploadedOn: "02 Jul 2026" },
      { name: "Service History Log.pdf", size: "3.4 MB", category: "Service History", uploadedOn: "02 Jul 2026" },
    ],
    requiredPhotos: ["Front View", "Back View", "Controller Panel", "Name Plate", "Chuck / Spindle", "Working Condition"],
    additionalRemarks: "Machine is under power and can be demonstrated under load at the seller site.",
  },
  {
    id: "MS-1005",
    title: "Okuma GENOS M560-V",
    brand: "Okuma",
    type: "Vertical Machining Center",
    category: "VMC Centers",
    categories: ["VMC", "Milling"],
    year: "2019",
    price: 9200000,
    location: "Coimbatore, TN",
    condition: "Excellent",
    hours: "7,100",
    origin: "Japan",
    status: "Live",
    views: 301,
    inquiries: 6,
    seller: "Kongu Engineering Works",
    listedOn: "2026-06-19",
    badge: "CERTIFIED",
    priceNote: "INSTALL INCLUDED",
    ctaLabel: "View Configuration Sheet",
    images: [`${IMG}/okuma_genos.jpg`, `${IMG}/vmc_machining_center.jpg`],
    overview: [
      "Okuma's GENOS M560-V pairs a rigid box-way structure with the OSP-P300 control and Thermo-Friendly Concept, holding dimensional stability through long unattended runs.",
      "Bought new by a tier-1 automotive supplier and maintained on a quarterly AMC. Original tooling and manuals included.",
    ],
    features: ["Thermo-Friendly Concept", "Collision Avoidance", "Through Spindle Coolant", "Box Ways"],
    description: "Tier-1 automotive use, quarterly AMC, original tooling included.",
    sellerInfo: seller({
      name: "Suresh Nair",
      company: "Kongu Engineering Works",
      mobile: "+91 94430 55219",
      whatsapp: "+91 94430 55219",
      email: "suresh@konguworks.in",
      gstNumber: "33AAECK4432D1ZN",
      panNumber: "AAECK4432D",
      address: "12 SIDCO Industrial Estate, Kurichi",
      city: "Coimbatore",
      state: "Tamil Nadu",
      pincode: "641021",
    }),
    details: details({
      machineType: "Vertical Machining Center",
      installationYear: "2019",
      countryOfOrigin: "Japan",
      controller: "Okuma OSP-P300MA",
      numberOfAxis: "3 Axis",
      machineCapacity: "1,050 / 560 / 460 mm",
      powerRequirement: "3-Phase 415V, 30 kVA",
      maxSpindleSpeed: "15,000 rpm",
      weight: "6,500 kg",
      lastServiceDate: "05 Jun 2026",
      accessoriesIncluded: "Tool holders, coolant chiller, manuals",
      serialNumber: "SN-M560V-3391",
    }),
    specs: specs({
      tableSize: "1,300 x 550 mm",
      lubricationSystem: "Automatic centralised",
      electricalPanelCondition: "Excellent",
      toolMagazineCapacity: "32 tools",
      servoMotors: "Okuma AC servo — healthy",
      toolChangerType: "Arm type ATC",
      ballScrewCondition: "Excellent",
      coolantSystem: "Flood + through spindle",
      guideways: "Box ways (Y/Z)",
      hydraulicSystem: "Working",
      otherSpecifications: "Thermo-Friendly Concept, rapids 40 m/min",
    }),
    commercial: commercial({}),
    documents: [
      { name: "Original Invoice.pdf", size: "1.4 MB", category: "Original Invoice", uploadedOn: "19 Jun 2026" },
      { name: "AMC Contract.pdf", size: "2.6 MB", category: "AMC Details", uploadedOn: "19 Jun 2026" },
    ],
    requiredPhotos: ["Front View", "Controller Panel", "Name Plate", "Working Condition"],
    additionalRemarks: "Installation and commissioning included in the quoted price.",
  },
  {
    id: "MS-1006",
    title: "Doosan DNM 5700",
    brand: "Doosan Machine Tools",
    type: "Vertical Machining Center",
    category: "VMC Centers",
    categories: ["VMC", "Milling"],
    year: "2020",
    price: 7800000,
    location: "Ahmedabad, GJ",
    condition: "Good",
    hours: "9,300",
    origin: "South Korea",
    status: "Pending Review",
    views: 0,
    inquiries: 0,
    seller: "Sabarmati Precision",
    listedOn: "2026-08-04",
    badge: "VERIFIED",
    priceNote: "EXCL. SHIPPING",
    ctaLabel: "Request Technical Audit",
    images: [`${IMG}/vmc_machining_center.jpg`, `${IMG}/haas_vf2.jpg`],
    overview: [
      "A large-envelope VMC that suits die work and long plates — 1,300 mm of X travel with a 1,300 kg table capacity.",
      "Single owner, used on two shifts in a general engineering shop. Ball screws and guideways checked clear at the last audit.",
    ],
    features: ["Rigid Tapping", "Programmable Coolant", "Chip Conveyor", "Spindle Chiller"],
    description: "Single owner, two-shift general engineering use.",
    sellerInfo: seller({
      name: "Meera Patel",
      company: "Sabarmati Precision",
      mobile: "+91 99250 33418",
      whatsapp: "+91 99250 33418",
      email: "meera@sabarmatiprec.in",
      gstNumber: "24AAJCS8890B1ZQ",
      panNumber: "AAJCS8890B",
      address: "88 Odhav GIDC Estate",
      city: "Ahmedabad",
      state: "Gujarat",
      pincode: "382415",
    }),
    details: details({
      machineType: "Vertical Machining Center",
      installationYear: "2020",
      countryOfOrigin: "South Korea",
      controller: "Fanuc 0i-MF Plus",
      numberOfAxis: "3 Axis",
      machineCapacity: "1,300 / 570 / 625 mm",
      powerRequirement: "3-Phase 415V, 26 kVA",
      maxSpindleSpeed: "12,000 rpm",
      weight: "7,300 kg",
      maintenanceStatus: "Irregular",
      lastServiceDate: "11 Mar 2026",
      accessoriesIncluded: "BT40 holders, chip conveyor",
      serialNumber: "SN-DNM5700-7724",
    }),
    specs: specs({
      tableSize: "1,500 x 570 mm",
      lubricationSystem: "Automatic",
      electricalPanelCondition: "Good",
      toolMagazineCapacity: "30 tools",
      servoMotors: "Fanuc AC servo",
      toolChangerType: "Arm type ATC",
      ballScrewCondition: "Good",
      coolantSystem: "Flood, 20 bar",
      guideways: "Roller guideways",
      hydraulicSystem: "Working",
      otherSpecifications: "Positioning accuracy ±0.005 mm",
    }),
    commercial: commercial({ taxInvoiceAvailable: false, ownerType: "Reseller" }),
    documents: [
      { name: "Ownership Proof.pdf", size: "0.7 MB", category: "Ownership Proof", uploadedOn: "04 Aug 2026" },
      { name: "GST Certificate.pdf", size: "0.4 MB", category: "GST Certificate", uploadedOn: "04 Aug 2026" },
    ],
    requiredPhotos: ["Front View", "Back View", "Controller Panel", "Name Plate"],
    additionalRemarks: "Complete documentation attached. Requesting priority listing.",
  },
  {
    id: "MS-1007",
    title: "Mazak QUICK TURN 250MY",
    brand: "Yamazaki Mazak",
    type: "CNC Turning Center",
    category: "Lathes",
    categories: ["Lathe", "CNC"],
    year: "2018",
    price: 6200000,
    location: "Pune, MH",
    condition: "Good",
    hours: "12,600",
    origin: "Japan",
    status: "Live",
    views: 268,
    inquiries: 4,
    seller: "Aerotech Solutions",
    listedOn: "2026-05-14",
    badge: "VERIFIED",
    priceNote: "EXCL. SHIPPING",
    ctaLabel: "Request Technical Audit",
    images: [`${IMG}/mazak_quick_turn.jpg`, `${IMG}/lathe_wasino.jpg`],
    overview: [
      "The QUICK TURN 250MY adds Y-axis and driven tooling to Mazak's proven turning platform, so milled flats and cross-holes finish without a second operation.",
      "Used on hydraulic component work. Turret and tailstock serviced in 2025; spindle bearings original and running within spec.",
    ],
    features: ["Driven Tooling", "Y-Axis", "Programmable Tailstock", "Parts Catcher"],
    description: "Hydraulic component production. Turret and tailstock serviced 2025.",
    sellerInfo: seller({
      name: "Marcus V. Sterling",
      company: "Aerotech Solutions Inc.",
      mobile: "+91 98220 41155",
      whatsapp: "+91 98220 41155",
      email: "marcus@aerotech.in",
      gstNumber: "27AABCA9021M1Z8",
      panNumber: "AABCA9021M",
      address: "Plot 18, Chakan Industrial Area Phase II",
      city: "Pune",
      state: "Maharashtra",
      pincode: "410501",
    }),
    details: details({
      machineType: "CNC Turning Center",
      installationYear: "2018",
      countryOfOrigin: "Japan",
      controller: "Mazatrol SmoothG",
      numberOfAxis: "4 Axis (X/Y/Z/C)",
      machineCapacity: "Ø 350 mm x 1,011 mm",
      powerRequirement: "3-Phase 415V, 28 kVA",
      maxSpindleSpeed: "4,000 rpm",
      weight: "5,900 kg",
      lastServiceDate: "22 Apr 2026",
      accessoriesIncluded: "10\" chuck, parts catcher, driven tool holders",
      serialNumber: "SN-QT250MY-1180",
    }),
    specs: specs({
      tableSize: "Not applicable",
      lubricationSystem: "Automatic",
      electricalPanelCondition: "Good",
      toolMagazineCapacity: "12 turret stations (all driven)",
      servoMotors: "Mazak AC servo",
      toolChangerType: "Turret",
      ballScrewCondition: "Good",
      coolantSystem: "Flood + through tool",
      guideways: "Box ways",
      hydraulicSystem: "Working",
      otherSpecifications: "Y-axis ±50 mm, programmable tailstock",
    }),
    commercial: commercial({}),
    documents: [
      { name: "Original Invoice.pdf", size: "1.0 MB", category: "Original Invoice", uploadedOn: "14 May 2026" },
    ],
    requiredPhotos: ["Front View", "Controller Panel", "Chuck / Spindle"],
    additionalRemarks: "Bar feeder available separately.",
  },
  {
    id: "MS-1008",
    title: "Doosan PUMA 2600SY",
    brand: "Doosan Machine Tools",
    type: "CNC Turning Center",
    category: "Lathes",
    categories: ["Lathe", "CNC"],
    year: "2019",
    price: 5500000,
    location: "Chennai, TN",
    condition: "Good",
    hours: "15,400",
    origin: "South Korea",
    status: "Sold",
    views: 610,
    inquiries: 15,
    seller: "Southern Machine Tools",
    listedOn: "2026-03-08",
    badge: "VERIFIED",
    priceNote: "EXCL. SHIPPING",
    ctaLabel: "Request Technical Audit",
    images: [`${IMG}/lathe_moriseiki.jpg`, `${IMG}/doosan_lynx.jpg`],
    overview: [
      "A sub-spindle, Y-axis turning center for complete machining of small to medium shafts and chucked parts in one clamping.",
      "Ran a single automotive part family on three shifts. Fully documented AMC history and a recent geometric accuracy report.",
    ],
    features: ["Sub Spindle", "Y-Axis", "Driven Tooling", "Parts Catcher"],
    description: "Sold to a verified buyer through MachSetu escrow.",
    sellerInfo: seller({
      name: "Anitha Raman",
      company: "Southern Machine Tools",
      mobile: "+91 90031 77820",
      whatsapp: "+91 90031 77820",
      email: "anitha@southernmt.in",
      gstNumber: "33AAFCS2210H1ZP",
      panNumber: "AAFCS2210H",
      address: "72 Ambattur Industrial Estate",
      city: "Chennai",
      state: "Tamil Nadu",
      pincode: "600058",
    }),
    details: details({
      machineType: "CNC Turning Center",
      installationYear: "2019",
      countryOfOrigin: "South Korea",
      controller: "Fanuc i Series",
      numberOfAxis: "5 Axis (X/Y/Z/C + sub)",
      machineCapacity: "Ø 400 mm x 780 mm",
      powerRequirement: "3-Phase 415V, 24 kVA",
      maxSpindleSpeed: "3,500 rpm",
      weight: "6,200 kg",
      lastServiceDate: "18 Feb 2026",
      accessoriesIncluded: "10\" chuck, parts catcher, bar feed interface",
      serialNumber: "SN-5510983C",
    }),
    specs: specs({
      tableSize: "Not applicable",
      lubricationSystem: "Automatic",
      electricalPanelCondition: "Good",
      toolMagazineCapacity: "12 turret stations (driven)",
      servoMotors: "Fanuc AC servo",
      toolChangerType: "Turret",
      ballScrewCondition: "Good",
      coolantSystem: "Flood, 15 bar",
      guideways: "Box ways",
      hydraulicSystem: "Working",
      otherSpecifications: "Y-axis ±52.5 mm, servo sub spindle",
    }),
    commercial: commercial({ negotiable: false }),
    documents: [
      { name: "Original Invoice.pdf", size: "1.1 MB", category: "Original Invoice", uploadedOn: "08 Mar 2026" },
      { name: "Geometric Accuracy Report.pdf", size: "2.8 MB", category: "Maintenance Records", uploadedOn: "08 Mar 2026" },
    ],
    requiredPhotos: ["Front View", "Back View", "Controller Panel", "Chuck / Spindle", "Name Plate"],
    additionalRemarks: "Completed sale — retained for reference.",
  },
  {
    id: "MS-1009",
    title: "Haas ST-20Y",
    brand: "Haas Automation",
    type: "CNC Lathe with Y-Axis",
    category: "Lathes",
    categories: ["Lathe", "CNC"],
    year: "2021",
    price: 4850000,
    location: "Ludhiana, PB",
    condition: "Excellent",
    hours: "3,800",
    origin: "USA",
    status: "Live",
    views: 195,
    inquiries: 3,
    seller: "Punjab Tooling Co.",
    listedOn: "2026-07-21",
    badge: "EXCELLENT CONDITION",
    priceNote: "INSTALL INCLUDED",
    ctaLabel: "View Configuration Sheet",
    images: [`${IMG}/lathe_wasino.jpg`, `${IMG}/mazak_quick_turn.jpg`],
    overview: [
      "A compact Y-axis turning center with live tooling — well suited to short-run precision work where a second op would otherwise be needed.",
      "Barely three years old with under 4,000 spindle hours. Still on the original Haas service contract, transferable to the buyer.",
    ],
    features: ["Live Tooling", "Y-Axis", "Servo Tailstock", "Chip Auger"],
    description: "Under 4,000 spindle hours. Original Haas service contract transferable.",
    sellerInfo: seller({
      name: "Rajesh Kumar",
      company: "Punjab Tooling Co.",
      mobile: "+91 98761 20034",
      whatsapp: "+91 98761 20034",
      email: "rajesh@punjabtooling.in",
      gstNumber: "03AACCP7781Q1ZK",
      panNumber: "AACCP7781Q",
      address: "Focal Point Phase VIII",
      city: "Ludhiana",
      state: "Punjab",
      pincode: "141010",
    }),
    details: details({
      machineType: "CNC Turning Center",
      installationYear: "2021",
      countryOfOrigin: "USA",
      controller: "Haas Next Generation Control",
      numberOfAxis: "4 Axis (X/Y/Z/C)",
      machineCapacity: "Ø 267 mm x 584 mm",
      powerRequirement: "3-Phase 415V, 18 kVA",
      maxSpindleSpeed: "4,000 rpm",
      weight: "3,765 kg",
      lastServiceDate: "30 Jun 2026",
      accessoriesIncluded: "8.3\" chuck, live tool holders, chip auger",
      serialNumber: "SN-ST20Y-4402",
    }),
    specs: specs({
      tableSize: "Not applicable",
      lubricationSystem: "Automatic",
      electricalPanelCondition: "Excellent",
      toolMagazineCapacity: "12 station BOT turret",
      servoMotors: "Haas AC servo — healthy",
      toolChangerType: "Turret",
      ballScrewCondition: "Excellent",
      coolantSystem: "Flood, high pressure ready",
      guideways: "Linear guideways",
      hydraulicSystem: "Not applicable",
      otherSpecifications: "Y-axis ±50.8 mm, servo tailstock",
    }),
    commercial: commercial({}),
    documents: [
      { name: "Original Invoice.pdf", size: "0.8 MB", category: "Original Invoice", uploadedOn: "21 Jul 2026" },
      { name: "Warranty Certificate.pdf", size: "0.5 MB", category: "Warranty (If Any)", uploadedOn: "21 Jul 2026" },
    ],
    requiredPhotos: ["Front View", "Back View", "Left Side View", "Right Side View", "Controller Panel", "Name Plate", "Chuck / Spindle"],
    additionalRemarks: "Service contract transfers with the machine.",
  },
  {
    id: "MS-1010",
    title: "Studer S33",
    brand: "Fritz Studer AG",
    type: "Universal Cylindrical Grinder",
    category: "Grinders",
    categories: ["Grinding"],
    year: "2017",
    price: 8800000,
    location: "Pune, MH",
    condition: "Excellent",
    hours: "8,900",
    origin: "Switzerland",
    status: "Live",
    views: 176,
    inquiries: 5,
    seller: "Deccan Grinding Systems",
    listedOn: "2026-06-05",
    badge: "CERTIFIED",
    priceNote: "INSTALL INCLUDED",
    ctaLabel: "Request Technical Audit",
    images: [`${IMG}/grinder_cylindrical.jpg`, `${IMG}/workshop_banner.jpg`],
    overview: [
      "The S33 is Studer's universal cylindrical grinder for medium-sized workpieces — external, internal and face grinding on a single B-axis platform.",
      "Housed in a climate-controlled grinding room since installation. Marposs in-process gauging and a full set of wheel adapters are included in the sale.",
    ],
    features: ["B-Axis Wheelhead", "In-Process Gauging", "CNC Dressing", "Internal Grinding Attachment"],
    description: "Climate-controlled grinding room since installation. Marposs gauging included.",
    sellerInfo: seller({
      name: "Deepak Joshi",
      company: "Deccan Grinding Systems",
      mobile: "+91 98600 71144",
      whatsapp: "+91 98600 71144",
      email: "deepak@deccangrind.in",
      gstNumber: "27AAKCD6654F1ZT",
      panNumber: "AAKCD6654F",
      address: "Unit 9, Bhosari MIDC",
      city: "Pune",
      state: "Maharashtra",
      pincode: "411026",
    }),
    details: details({
      machineType: "Universal Cylindrical Grinder",
      installationYear: "2017",
      countryOfOrigin: "Switzerland",
      controller: "Fanuc 31i-B with StuderWIN",
      numberOfAxis: "3 Axis (X/Z/B)",
      machineCapacity: "1,000 mm centres, 175 mm centre height",
      powerRequirement: "3-Phase 415V, 20 kVA",
      maxSpindleSpeed: "Wheel 1,800 rpm",
      weight: "4,600 kg",
      lastServiceDate: "28 May 2026",
      accessoriesIncluded: "Wheel adapters, Marposs gauging, diamond rolls",
      serialNumber: "SN-S33-2216",
    }),
    specs: specs({
      tableSize: "Not applicable",
      lubricationSystem: "Automatic centralised",
      electricalPanelCondition: "Excellent",
      toolMagazineCapacity: "Wheel 500 x 63 x 203 mm",
      servoMotors: "Linear drive — healthy",
      toolChangerType: "Manual wheel change",
      ballScrewCondition: "Excellent",
      coolantSystem: "Paper band filtration",
      guideways: "StuderGuide with linear drive",
      hydraulicSystem: "Working",
      otherSpecifications: "B-axis ±30°, roundness 0.0005 mm",
    }),
    commercial: commercial({}),
    documents: [
      { name: "Original Invoice.pdf", size: "1.3 MB", category: "Original Invoice", uploadedOn: "05 Jun 2026" },
      { name: "Calibration Certificate.pdf", size: "1.9 MB", category: "Maintenance Records", uploadedOn: "05 Jun 2026" },
    ],
    requiredPhotos: ["Front View", "Controller Panel", "Name Plate", "Working Condition"],
    additionalRemarks: "Installation and alignment included.",
  },
  {
    id: "MS-1011",
    title: "Okamoto ACC-1224DX",
    brand: "Okamoto",
    type: "Precision Surface Grinder",
    category: "Grinders",
    categories: ["Grinding"],
    year: "2019",
    price: 3200000,
    location: "Rajkot, GJ",
    condition: "Good",
    hours: "6,700",
    origin: "Japan",
    status: "Pending Review",
    views: 0,
    inquiries: 0,
    seller: "Fortune Gold Machine Tools",
    listedOn: "2026-08-06",
    badge: "VERIFIED",
    priceNote: "EXCL. SHIPPING",
    ctaLabel: "Request Technical Audit",
    images: [`${IMG}/grinder_surface.jpg`, `${IMG}/workshop_banner.jpg`],
    overview: [
      "A workhorse hydraulic surface grinder with automatic three-axis operation, widely used in Indian tool rooms for die plates and precision flats.",
      "Comes with the original electromagnetic chuck, coolant system with magnetic separator, and a spare wheel set.",
    ],
    features: ["Auto 3-Axis", "Electromagnetic Chuck", "Magnetic Separator", "Auto Down Feed"],
    description: "Tool room use. Original chuck and spare wheel set included.",
    sellerInfo: seller({
      name: "Pappu Singh",
      company: "Fortune Gold Machine Tools",
      mobile: "+91 84015 03169",
      whatsapp: "+91 84015 03169",
      email: "sales@fortunegold.in",
      gstNumber: "24AAACF1234K1ZV",
      panNumber: "AAACF1234K",
      address: "Fortune Gold, Metoda, Lodhika",
      city: "Rajkot",
      state: "Gujarat",
      pincode: "360021",
    }),
    details: details({
      machineType: "Precision Surface Grinder",
      installationYear: "2019",
      countryOfOrigin: "Japan",
      controller: "Okamoto digital, 3-axis auto",
      numberOfAxis: "3 Axis (X/Y/Z auto)",
      machineCapacity: "300 x 600 mm table",
      powerRequirement: "3-Phase 415V, 11 kVA",
      maxSpindleSpeed: "1,800 rpm",
      weight: "2,300 kg",
      lastServiceDate: "15 Jul 2026",
      accessoriesIncluded: "Electromagnetic chuck, spare wheel set, coolant unit",
      serialNumber: "SN-ACC1224-9910",
    }),
    specs: specs({
      tableSize: "300 x 600 mm",
      lubricationSystem: "Manual",
      electricalPanelCondition: "Good",
      toolMagazineCapacity: "Wheel 355 x 38 x 127 mm",
      servoMotors: "Not applicable",
      toolChangerType: "Manual wheel change",
      ballScrewCondition: "Good",
      coolantSystem: "Magnetic separator + paper filter",
      guideways: "Hardened and ground V-flat",
      hydraulicSystem: "Working",
      otherSpecifications: "Down feed increment 0.001 mm",
    }),
    commercial: commercial({ financePending: true }),
    documents: [
      { name: "Original Invoice.pdf", size: "0.9 MB", category: "Original Invoice", uploadedOn: "06 Aug 2026" },
      { name: "Ownership Proof.pdf", size: "0.6 MB", category: "Ownership Proof", uploadedOn: "06 Aug 2026" },
    ],
    requiredPhotos: ["Front View", "Controller Panel", "Name Plate"],
    additionalRemarks: "Original chuck and spare wheel set included.",
  },
  {
    id: "MS-1012",
    title: "Ghiringhelli M200 SP",
    brand: "Ghiringhelli",
    type: "Centreless Grinding Machine",
    category: "Grinders",
    categories: ["Grinding"],
    year: "2016",
    price: 4100000,
    location: "Bengaluru, KA",
    condition: "Good",
    hours: "13,100",
    origin: "Italy",
    status: "Live",
    views: 143,
    inquiries: 2,
    seller: "Precision Dynamics",
    listedOn: "2026-04-27",
    badge: "VERIFIED",
    priceNote: "EXCL. SHIPPING",
    ctaLabel: "View Configuration Sheet",
    images: [`${IMG}/grinder_centerless.jpg`, `${IMG}/workshop_banner.jpg`],
    overview: [
      "A through-feed and in-feed centreless grinder built for high-volume pin, shaft and bearing-race work.",
      "Rebuilt wheel spindle in 2024 with documentation. Sold with work rests, blades and the original dressing attachments.",
    ],
    features: ["Through-Feed", "In-Feed", "CNC Dressing", "Paper Band Filtration"],
    description: "High-volume pin and bearing-race work. Wheel spindle rebuilt 2024.",
    sellerInfo: seller({
      name: "Vikram Shetty",
      company: "Precision Dynamics",
      mobile: "+91 98450 66712",
      whatsapp: "+91 98450 66712",
      email: "vikram@precisiondyn.in",
      gstNumber: "29AAGCP5567L1ZR",
      panNumber: "AAGCP5567L",
      address: "44 Peenya Industrial Area Phase III",
      city: "Bengaluru",
      state: "Karnataka",
      pincode: "560058",
    }),
    details: details({
      machineType: "Centreless Grinding Machine",
      installationYear: "2016",
      countryOfOrigin: "Italy",
      controller: "Siemens PLC with touch HMI",
      numberOfAxis: "2 CNC Axis",
      machineCapacity: "Ø 0.5 – 100 mm",
      powerRequirement: "3-Phase 415V, 25 kVA",
      maxSpindleSpeed: "1,450 rpm",
      weight: "4,100 kg",
      maintenanceStatus: "Regular",
      lastServiceDate: "09 Apr 2026",
      accessoriesIncluded: "Work rests, blades, dressing attachments",
      serialNumber: "SN-M200SP-6641",
    }),
    specs: specs({
      tableSize: "Not applicable",
      lubricationSystem: "Automatic",
      electricalPanelCondition: "Good",
      toolMagazineCapacity: "Wheel 500 x 200 x 304.8 mm",
      servoMotors: "Siemens servo",
      toolChangerType: "Manual wheel change",
      ballScrewCondition: "Good",
      coolantSystem: "Tank with paper band filter",
      guideways: "Hardened slideways",
      hydraulicSystem: "Working",
      otherSpecifications: "Roundness 0.001 mm, regulating wheel 250 x 200 mm",
    }),
    commercial: commercial({ ownerType: "Dealer" }),
    documents: [
      { name: "Spindle Rebuild Report.pdf", size: "1.7 MB", category: "Maintenance Records", uploadedOn: "27 Apr 2026" },
    ],
    requiredPhotos: ["Front View", "Controller Panel", "Working Condition"],
    additionalRemarks: "Work rests and blades included.",
  },
  {
    id: "MS-1013",
    title: "Sodick AG400L",
    brand: "Sodick",
    type: "Wire Cut EDM",
    category: "EDM",
    categories: ["EDM"],
    year: "2019",
    price: 5800000,
    location: "Chennai, TN",
    condition: "Excellent",
    hours: "5,600",
    origin: "Japan",
    status: "Live",
    views: 232,
    inquiries: 6,
    seller: "Southern Machine Tools",
    listedOn: "2026-07-11",
    badge: "CERTIFIED",
    priceNote: "INSTALL INCLUDED",
    ctaLabel: "Request Technical Audit",
    images: [`${IMG}/wire_edm_ona.jpg`, `${IMG}/wire_edm_robofil.jpg`],
    overview: [
      "Sodick's AG400L runs linear motor drives on every axis, so there are no ball screws to wear and long-term positioning accuracy holds without backlash compensation.",
      "Used for carbide punch and die work in a tool room. Includes the water chiller, filter housing and a stock of consumables.",
    ],
    features: ["Linear Motor Drives", "Auto Wire Threading", "Anti-Electrolysis", "Submerged Cutting"],
    description: "Carbide punch and die work. Chiller, filter housing and consumables included.",
    sellerInfo: seller({
      name: "Anitha Raman",
      company: "Southern Machine Tools",
      mobile: "+91 90031 77820",
      whatsapp: "+91 90031 77820",
      email: "anitha@southernmt.in",
      gstNumber: "33AAFCS2210H1ZP",
      panNumber: "AAFCS2210H",
      address: "72 Ambattur Industrial Estate",
      city: "Chennai",
      state: "Tamil Nadu",
      pincode: "600058",
    }),
    details: details({
      machineType: "Wire Cut EDM",
      installationYear: "2019",
      countryOfOrigin: "Japan",
      controller: "Sodick LN2W",
      numberOfAxis: "5 Axis (X/Y/Z/U/V)",
      machineCapacity: "400 / 300 / 250 mm",
      powerRequirement: "3-Phase 415V, 15 kVA",
      maxSpindleSpeed: "Not applicable",
      weight: "3,400 kg",
      lastServiceDate: "01 Jul 2026",
      accessoriesIncluded: "Water chiller, filter housing, wire spools",
      serialNumber: "SN-AG400L-3308",
    }),
    specs: specs({
      tableSize: "810 x 700 x 250 mm max workpiece",
      lubricationSystem: "Not applicable",
      electricalPanelCondition: "Excellent",
      toolMagazineCapacity: "Wire Ø 0.10 – 0.30 mm",
      servoMotors: "Linear motor, all axes",
      toolChangerType: "Auto wire threading",
      ballScrewCondition: "Not applicable (linear drive)",
      coolantSystem: "Deionised water with chiller",
      guideways: "Linear motor guides",
      hydraulicSystem: "Not applicable",
      otherSpecifications: "Taper ±15° / 80 mm, Ra 0.4 µm, anti-electrolysis",
    }),
    commercial: commercial({}),
    documents: [
      { name: "Original Invoice.pdf", size: "1.2 MB", category: "Original Invoice", uploadedOn: "11 Jul 2026" },
      { name: "Operator Manual.pdf", size: "12.1 MB", category: "Machine Manual", uploadedOn: "11 Jul 2026" },
    ],
    requiredPhotos: ["Front View", "Controller Panel", "Name Plate", "Working Condition"],
    additionalRemarks: "Consumable stock transfers with the machine.",
  },
  {
    id: "MS-1014",
    title: "Mitsubishi MV1200R",
    brand: "Mitsubishi Electric",
    type: "Wire Cut EDM",
    category: "EDM",
    categories: ["EDM"],
    year: "2020",
    price: 6400000,
    location: "Pune, MH",
    condition: "Excellent",
    hours: "4,100",
    origin: "Japan",
    status: "Live",
    views: 209,
    inquiries: 4,
    seller: "Deccan Grinding Systems",
    listedOn: "2026-07-29",
    badge: "EXCELLENT CONDITION",
    priceNote: "EXCL. SHIPPING",
    ctaLabel: "View Configuration Sheet",
    images: [`${IMG}/wire_edm_robofil.jpg`, `${IMG}/wire_edm_ona.jpg`],
    overview: [
      "The MV1200R is Mitsubishi's R-series wire EDM with a cylindrical drive system and tubular ceramic construction that resists thermal drift during long unattended cuts.",
      "Low-hour machine from a precision mould shop. Wire threading is reliable from cold; chiller serviced in 2026.",
    ],
    features: ["Auto Wire Threading", "Digital-FS Generator", "Optimum Power Control", "Anti-Electrolysis"],
    description: "Low-hour machine from a precision mould shop.",
    sellerInfo: seller({
      name: "Deepak Joshi",
      company: "Deccan Grinding Systems",
      mobile: "+91 98600 71144",
      whatsapp: "+91 98600 71144",
      email: "deepak@deccangrind.in",
      gstNumber: "27AAKCD6654F1ZT",
      panNumber: "AAKCD6654F",
      address: "Unit 9, Bhosari MIDC",
      city: "Pune",
      state: "Maharashtra",
      pincode: "411026",
    }),
    details: details({
      machineType: "Wire Cut EDM",
      installationYear: "2020",
      countryOfOrigin: "Japan",
      controller: "Mitsubishi M800 series",
      numberOfAxis: "5 Axis (X/Y/Z/U/V)",
      machineCapacity: "400 / 300 / 220 mm",
      powerRequirement: "3-Phase 415V, 14 kVA",
      maxSpindleSpeed: "Not applicable",
      weight: "2,900 kg",
      lastServiceDate: "12 Jun 2026",
      accessoriesIncluded: "Chiller, wire spools, filters",
      serialNumber: "SN-MV1200R-7781",
    }),
    specs: specs({
      tableSize: "1,050 x 820 x 215 mm max workpiece",
      lubricationSystem: "Not applicable",
      electricalPanelCondition: "Excellent",
      toolMagazineCapacity: "Wire Ø 0.10 – 0.30 mm",
      servoMotors: "Cylindrical AC servo",
      toolChangerType: "Auto wire threading (annealed cut)",
      ballScrewCondition: "Excellent",
      coolantSystem: "Deionised water with chiller",
      guideways: "Tubular ceramic construction",
      hydraulicSystem: "Not applicable",
      otherSpecifications: "Taper ±15° / 100 mm, Ra 0.32 µm, Digital-FS",
    }),
    commercial: commercial({}),
    documents: [
      { name: "Original Invoice.pdf", size: "1.0 MB", category: "Original Invoice", uploadedOn: "29 Jul 2026" },
    ],
    requiredPhotos: ["Front View", "Controller Panel", "Name Plate"],
    additionalRemarks: "Chiller serviced in 2026.",
  },
  {
    id: "MS-1015",
    title: "Makino EDNC6",
    brand: "Makino",
    type: "Sinker EDM / Small Hole Driller",
    category: "EDM",
    categories: ["EDM", "Drilling"],
    year: "2018",
    price: 3750000,
    location: "Ahmedabad, GJ",
    condition: "Good",
    hours: "10,200",
    origin: "Japan",
    status: "Rejected",
    views: 0,
    inquiries: 0,
    seller: "Sabarmati Precision",
    listedOn: "2026-07-18",
    badge: "VERIFIED",
    priceNote: "EXCL. SHIPPING",
    ctaLabel: "Request Technical Audit",
    images: [`${IMG}/edm_small_hole.jpg`, `${IMG}/wire_edm_ona.jpg`],
    overview: [
      "A compact sinker EDM used for cavity work and start holes, with the small-hole drilling head fitted for wire EDM pre-drilling.",
      "Steady toolroom use on single shifts. Dielectric system flushed and filters replaced before listing.",
    ],
    features: ["Small Hole Drilling", "Fire Suppression", "Paper Filtration", "Graphite Capable"],
    description: "Toolroom use on single shifts. Dielectric flushed before listing.",
    sellerInfo: seller({
      name: "Meera Patel",
      company: "Sabarmati Precision",
      mobile: "+91 99250 33418",
      whatsapp: "+91 99250 33418",
      email: "meera@sabarmatiprec.in",
      gstNumber: "24AAJCS8890B1ZQ",
      panNumber: "AAJCS8890B",
      address: "88 Odhav GIDC Estate",
      city: "Ahmedabad",
      state: "Gujarat",
      pincode: "382415",
    }),
    details: details({
      machineType: "Sinker EDM with small hole drilling",
      installationYear: "2018",
      countryOfOrigin: "Japan",
      controller: "Makino MGH",
      numberOfAxis: "3 Axis (X/Y/Z)",
      machineCapacity: "300 / 250 / 250 mm",
      powerRequirement: "3-Phase 415V, 12 kVA",
      maxSpindleSpeed: "Not applicable",
      weight: "2,100 kg",
      maintenanceStatus: "Irregular",
      lastServiceDate: "05 May 2026",
      accessoriesIncluded: "Electrode holders, CO₂ suppression bottle",
      serialNumber: "SN-EDNC6-1123",
    }),
    specs: specs({
      tableSize: "700 x 450 x 300 mm work tank",
      lubricationSystem: "Not applicable",
      electricalPanelCondition: "Average",
      toolMagazineCapacity: "Electrode up to 50 kg",
      servoMotors: "Makino AC servo",
      toolChangerType: "Manual electrode change",
      ballScrewCondition: "Good",
      coolantSystem: "EDM oil with paper filter",
      guideways: "Hardened slideways",
      hydraulicSystem: "Not applicable",
      otherSpecifications: "Discharge 40 A, Ra 0.2 µm, hole Ø 0.3 – 3.0 mm",
    }),
    commercial: commercial({ taxInvoiceAvailable: false, ownerType: "Reseller" }),
    documents: [
      { name: "Ownership Proof.pdf", size: "0.5 MB", category: "Ownership Proof", uploadedOn: "18 Jul 2026" },
    ],
    requiredPhotos: ["Front View", "Name Plate"],
    additionalRemarks: "Serial plate does not match the invoice — rejected pending clarification.",
  },
];

/* ---------------------------------------------------------------- users -- */

export const USERS: User[] = [
  { id: "U-2201", name: "Pappu Singh", designation: "Proprietor", company: "Fortune Gold Machine Tools", email: "sales@fortunegold.in", phone: "+91 84015 03169", whatsapp: "+91 84015 03169", address: "Fortune Gold, Metoda, Lodhika", city: "Rajkot", state: "Gujarat", pincode: "360021", gstin: "24AAACF1234K1ZV", pan: "AAACF1234K", role: "Seller", status: "Active", listings: 2, orders: 0, joinedOn: "2025-11-04" },
  { id: "U-2202", name: "Marcus V. Sterling", designation: "Senior Procurement Director", company: "Aerotech Solutions Inc.", email: "marcus@aerotech.in", phone: "+91 98220 41155", whatsapp: "+91 98220 41155", address: "Plot 18, Chakan Industrial Area Phase II", city: "Pune", state: "Maharashtra", pincode: "410501", gstin: "27AABCA9021M1Z8", pan: "AABCA9021M", role: "Both", status: "Active", listings: 2, orders: 12, joinedOn: "2025-08-22" },
  { id: "U-2203", name: "Rajesh Kumar", designation: "Plant Head", company: "Punjab Tooling Co.", email: "rajesh@punjabtooling.in", phone: "+91 98761 20034", whatsapp: "+91 98761 20034", address: "Focal Point Phase VIII", city: "Ludhiana", state: "Punjab", pincode: "141010", gstin: "03AACCP7781Q1ZK", pan: "AACCP7781Q", role: "Seller", status: "Active", listings: 1, orders: 2, joinedOn: "2026-01-17" },
  { id: "U-2204", name: "Anitha Raman", designation: "Managing Partner", company: "Southern Machine Tools", email: "anitha@southernmt.in", phone: "+91 90031 77820", whatsapp: "+91 90031 77820", address: "72 Ambattur Industrial Estate", city: "Chennai", state: "Tamil Nadu", pincode: "600058", gstin: "33AAFCS2210H1ZP", pan: "AAFCS2210H", role: "Both", status: "Active", listings: 3, orders: 7, joinedOn: "2025-06-30" },
  { id: "U-2205", name: "Vikram Shetty", designation: "Director", company: "Precision Dynamics", email: "vikram@precisiondyn.in", phone: "+91 98450 66712", whatsapp: "+91 98450 66712", address: "44 Peenya Industrial Area Phase III", city: "Bengaluru", state: "Karnataka", pincode: "560058", gstin: "29AAGCP5567L1ZR", pan: "AAGCP5567L", role: "Seller", status: "Active", listings: 2, orders: 1, joinedOn: "2025-09-12" },
  { id: "U-2206", name: "Meera Patel", designation: "Operations Manager", company: "Sabarmati Precision", email: "meera@sabarmatiprec.in", phone: "+91 99250 33418", whatsapp: "+91 99250 33418", address: "88 Odhav GIDC Estate", city: "Ahmedabad", state: "Gujarat", pincode: "382415", gstin: "24AAJCS8890B1ZQ", pan: "AAJCS8890B", role: "Seller", status: "Pending KYC", listings: 2, orders: 0, joinedOn: "2026-07-28" },
  { id: "U-2207", name: "Suresh Nair", designation: "Works Manager", company: "Kongu Engineering Works", email: "suresh@konguworks.in", phone: "+91 94430 55219", whatsapp: "+91 94430 55219", address: "12 SIDCO Industrial Estate, Kurichi", city: "Coimbatore", state: "Tamil Nadu", pincode: "641021", gstin: "33AAECK4432D1ZN", pan: "AAECK4432D", role: "Both", status: "Active", listings: 1, orders: 4, joinedOn: "2025-12-05" },
  { id: "U-2208", name: "Deepak Joshi", designation: "Proprietor", company: "Deccan Grinding Systems", email: "deepak@deccangrind.in", phone: "+91 98600 71144", whatsapp: "+91 98600 71144", address: "Unit 9, Bhosari MIDC", city: "Pune", state: "Maharashtra", pincode: "411026", gstin: "27AAKCD6654F1ZT", pan: "AAKCD6654F", role: "Seller", status: "Active", listings: 2, orders: 0, joinedOn: "2026-02-19" },
  { id: "U-2209", name: "Farhan Qureshi", designation: "Purchase Head", company: "Qureshi Auto Components", email: "farhan@qureshiauto.in", phone: "+91 93220 84470", whatsapp: "+91 93220 84470", address: "Gala 4, Andheri MIDC", city: "Mumbai", state: "Maharashtra", pincode: "400093", gstin: "27AADCQ1102J1ZM", pan: "AADCQ1102J", role: "Buyer", status: "Active", listings: 0, orders: 9, joinedOn: "2025-10-08" },
  { id: "U-2210", name: "Kavita Desai", designation: "Procurement Broker", company: "Desai Brokerage", email: "kavita@desaibrokers.in", phone: "+91 98795 21160", whatsapp: "+91 98795 21160", address: "301 Ring Road Commercial", city: "Surat", state: "Gujarat", pincode: "395002", gstin: "24AAHCD3345N1ZY", pan: "AAHCD3345N", role: "Broker", status: "Active", listings: 0, orders: 0, joinedOn: "2026-03-14" },
  { id: "U-2211", name: "Imran Shaikh", designation: "Owner", company: "Shaikh Fabricators", email: "imran@shaikhfab.in", phone: "+91 90040 12298", whatsapp: "+91 90040 12298", address: "Plot 22, Satpur MIDC", city: "Nashik", state: "Maharashtra", pincode: "422007", gstin: "27AAFCS9987R1ZL", pan: "AAFCS9987R", role: "Buyer", status: "Suspended", listings: 0, orders: 1, joinedOn: "2026-04-02" },
  { id: "U-2212", name: "Nisha Verma", designation: "Toolroom In-Charge", company: "Verma Toolroom", email: "nisha@vermatoolroom.in", phone: "+91 99100 45523", whatsapp: "+91 99100 45523", address: "Sector 24, Industrial Area", city: "Faridabad", state: "Haryana", pincode: "121005", gstin: "06AAGCV2214P1ZB", pan: "AAGCV2214P", role: "Buyer", status: "Pending KYC", listings: 0, orders: 0, joinedOn: "2026-08-01" },
];

/* -------------------------------------------------------- sell requests -- */

/** Requests reuse the catalogue record so the desk sees the full submission. */
function requestFrom(
  product: Product,
  overrides: Partial<SellRequest>,
): SellRequest {
  return {
    id: `REQ-${product.id.slice(3)}`,
    machine: product.title,
    brand: product.brand,
    model: product.details.serialNumber,
    category: product.category,
    categories: product.categories,
    year: product.year,
    askingPrice: product.price,
    condition: product.condition,
    hours: product.hours,
    city: product.location,
    seller: product.seller,
    status: "Awaiting Review",
    submittedOn: product.listedOn,
    note: product.additionalRemarks,
    description: product.description,
    images: product.images,
    documents: product.documents,
    requiredPhotos: product.requiredPhotos,
    sellerInfo: product.sellerInfo,
    details: product.details,
    specs: product.specs,
    commercial: product.commercial,
    inspection: null,
    ...overrides,
  };
}

const byId = (id: string) => PRODUCTS.find((p) => p.id === id)!;

export const SELL_REQUESTS: SellRequest[] = [
  requestFrom(byId("MS-1006"), { id: "REQ-5510", submittedOn: "2026-08-04" }),
  requestFrom(byId("MS-1011"), { id: "REQ-5511", submittedOn: "2026-08-06" }),
  requestFrom(byId("MS-1004"), {
    id: "REQ-5512",
    status: "Inspection Scheduled",
    submittedOn: "2026-08-01",
    note: "Inspection booked for 12 Aug with R. Deshmukh.",
    inspection: FULL_INSPECTION,
  }),
  requestFrom(byId("MS-1013"), {
    id: "REQ-5514",
    status: "Inspection Scheduled",
    submittedOn: "2026-07-30",
    note: "Awaiting dielectric system report.",
  }),
  requestFrom(byId("MS-1015"), {
    id: "REQ-5515",
    status: "Rejected",
    submittedOn: "2026-07-18",
  }),
  requestFrom(byId("MS-1009"), {
    id: "REQ-5516",
    status: "Approved",
    submittedOn: "2026-07-21",
    note: "Approved and published as MS-1009.",
    inspection: FULL_INSPECTION,
  }),
];

/* ------------------------------------------------------------ inquiries -- */

export const INQUIRIES: Inquiry[] = [
  { id: "RFQ-4471", machine: "DMG MORI DMU 50", brand: "DMG MORI", image: `${IMG}/dmg_cmx_1100v.jpg`, specs: ["Travel 650mm", "20,000 RPM", "Siemens 840D", "Qty 1"], buyer: "Marcus V. Sterling", company: "Aerotech Solutions Inc.", city: "Pune, MH", budget: 15000000, quoted: 14500000, status: "Quote Received", broker: "Kavita Desai", responseNote: "Vendor confirmed availability. Quote valid for 14 days.", raisedOn: "2026-07-26", lastActivity: "2026-08-05" },
  { id: "RFQ-4472", machine: "Haas VF-2SS", brand: "Haas Automation", image: `${IMG}/haas_vf2ss.jpg`, specs: ["30\" x 16\" x 20\"", "12,000 RPM", "CT 40", "Qty 1"], buyer: "Farhan Qureshi", company: "Qureshi Auto Components", city: "Mumbai, MH", budget: 7500000, quoted: 7050000, status: "Negotiating", broker: "Kavita Desai", responseNote: "Counter-offer sent. Awaiting vendor confirmation.", raisedOn: "2026-07-24", lastActivity: "2026-08-06" },
  { id: "RFQ-4473", machine: "Okuma GENOS M560-V", brand: "Okuma", image: `${IMG}/okuma_genos.jpg`, specs: ["1050mm X travel", "15,000 RPM", "Qty 1"], buyer: "Suresh Nair", company: "Kongu Engineering Works", city: "Coimbatore, TN", budget: 9500000, quoted: null, status: "Broker Assigned", broker: "Kavita Desai", responseNote: "Technical sourcing team is verifying compatibility.", raisedOn: "2026-08-02", lastActivity: "2026-08-04" },
  { id: "RFQ-4474", machine: "Sodick AG400L", brand: "Sodick", image: `${IMG}/wire_edm_ona.jpg`, specs: ["400/300/250 mm", "Taper ±15°", "Qty 1"], buyer: "Nisha Verma", company: "Verma Toolroom", city: "Faridabad, HR", budget: 6000000, quoted: null, status: "New", broker: null, responseNote: "Awaiting broker assignment.", raisedOn: "2026-08-07", lastActivity: "2026-08-07" },
  { id: "RFQ-4475", machine: "Studer S33", brand: "Fritz Studer AG", image: `${IMG}/grinder_cylindrical.jpg`, specs: ["1000mm centres", "B-axis", "Qty 1"], buyer: "Vikram Shetty", company: "Precision Dynamics", city: "Bengaluru, KA", budget: 9000000, quoted: 8800000, status: "Quote Received", broker: "Kavita Desai", responseNote: "Quote issued with installation included.", raisedOn: "2026-07-19", lastActivity: "2026-08-03" },
  { id: "RFQ-4476", machine: "Doosan PUMA 2600SY", brand: "Doosan Machine Tools", image: `${IMG}/lathe_moriseiki.jpg`, specs: ["Chuck 10\"", "Sub spindle", "Qty 2"], buyer: "Anitha Raman", company: "Southern Machine Tools", city: "Chennai, TN", budget: 5600000, quoted: 5500000, status: "Closed", broker: "Kavita Desai", responseNote: "Converted to order ORD-71044.", raisedOn: "2026-06-11", lastActivity: "2026-07-02" },
  { id: "RFQ-4477", machine: "Mazak HCN-4000", brand: "Yamazaki Mazak", image: `${IMG}/hmc_horizontal.jpg`, specs: ["Pallet 400mm", "40 tools", "Qty 1"], buyer: "Imran Shaikh", company: "Shaikh Fabricators", city: "Nashik, MH", budget: 9000000, quoted: 10500000, status: "Lost", broker: "Kavita Desai", responseNote: "Buyer budget below the seller's floor price.", raisedOn: "2026-06-02", lastActivity: "2026-06-28" },
  { id: "RFQ-4478", machine: "Mitsubishi MV1200R", brand: "Mitsubishi Electric", image: `${IMG}/wire_edm_robofil.jpg`, specs: ["400/300/220 mm", "Auto threading", "Qty 1"], buyer: "Farhan Qureshi", company: "Qureshi Auto Components", city: "Mumbai, MH", budget: 6800000, quoted: null, status: "Awaiting Quote", broker: null, responseNote: "Detailed audit of lead times in progress.", raisedOn: "2026-08-06", lastActivity: "2026-08-06" },
  { id: "RFQ-4479", machine: "Industrial Laser Cutter", brand: "Trumpf", image: null, specs: ["6kW fiber", "3000 x 1500mm bed", "Qty 1"], buyer: "Nisha Verma", company: "Verma Toolroom", city: "Faridabad, HR", budget: 12000000, quoted: null, status: "Expired", broker: null, responseNote: "No vendor response within the 21-day window.", raisedOn: "2026-06-20", lastActivity: "2026-07-11" },
];

/* --------------------------------------------------------------- orders -- */

export const ORDERS: Order[] = [
  { id: "ORD-88219", machine: "DMG MORI DMU 50", image: `${IMG}/dmg_cmx_1100v.jpg`, buyer: "Aerotech Solutions Inc.", seller: "Deccan Grinding Systems", amount: 15412500, stage: "Under Review", placedOn: "2026-08-02", destination: "Pune, MH" },
  { id: "ORD-90122", machine: "Haas VF-2SS", image: `${IMG}/haas_vf2ss.jpg`, buyer: "Qureshi Auto Components", seller: "Fortune Gold Machine Tools", amount: 7548150, stage: "Price Confirmed", placedOn: "2026-07-28", destination: "Mumbai, MH" },
  { id: "ORD-71044", machine: "Doosan PUMA 2600SY", image: `${IMG}/lathe_moriseiki.jpg`, buyer: "Southern Machine Tools", seller: "Punjab Tooling Co.", amount: 5893700, stage: "Delivered", placedOn: "2026-06-12", destination: "Chennai, TN" },
  { id: "ORD-66310", machine: "Ghiringhelli M200 SP", image: `${IMG}/grinder_centerless.jpg`, buyer: "Verma Toolroom", seller: "Precision Dynamics", amount: 4398530, stage: "Machine Reserved", placedOn: "2026-07-15", destination: "Faridabad, HR" },
  { id: "ORD-66450", machine: "Okuma GENOS M560-V", image: `${IMG}/okuma_genos.jpg`, buyer: "Kongu Engineering Works", seller: "Kongu Engineering Works", amount: 9862300, stage: "Delivery Scheduled", placedOn: "2026-07-09", destination: "Coimbatore, TN" },
];

/* ------------------------------------------------------------- activity -- */

export const REVENUE_TREND = [
  { month: "Sep", value: 18200000 },
  { month: "Oct", value: 21500000 },
  { month: "Nov", value: 19800000 },
  { month: "Dec", value: 26400000 },
  { month: "Jan", value: 24100000 },
  { month: "Feb", value: 29700000 },
  { month: "Mar", value: 33200000 },
  { month: "Apr", value: 28900000 },
  { month: "May", value: 35600000 },
  { month: "Jun", value: 41200000 },
  { month: "Jul", value: 38700000 },
  { month: "Aug", value: 44300000 },
];

export interface ActivityEntry {
  id: string;
  actor: string;
  action: string;
  target: string;
  at: string;
  tone: "accent" | "navy" | "success" | "danger";
}

export const ACTIVITY: ActivityEntry[] = [
  { id: "A1", actor: "Meera Patel", action: "submitted a listing", target: "Okamoto ACC-1224DX", at: "2026-08-07", tone: "accent" },
  { id: "A2", actor: "Nisha Verma", action: "raised an inquiry on", target: "Sodick AG400L", at: "2026-08-07", tone: "navy" },
  { id: "A3", actor: "R. Deshmukh", action: "completed inspection for", target: "Haas VF-2SS", at: "2026-08-06", tone: "success" },
  { id: "A4", actor: "Farhan Qureshi", action: "countered the quote on", target: "Haas VF-2SS", at: "2026-08-06", tone: "navy" },
  { id: "A5", actor: "Admin", action: "rejected the submission", target: "Makino EDNC6", at: "2026-08-05", tone: "danger" },
  { id: "A6", actor: "Marcus V. Sterling", action: "placed order", target: "ORD-88219", at: "2026-08-02", tone: "success" },
];
